[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "reinforce"
version = "0.0.1"
description = ""
dependencies = [
    "gymnasium ==1.2.1",
    "moviepy ==2.2.1",
    "numpy ==2.3.4",
    "pygame ==2.6.1",
    "tensorboard ==2.20.0",
    "torch ==2.9.0",
]
