[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "reinforce"
version = "0.0.1"
description = ""
dependencies = [
    "numpy ==2.3.4",
    "torch ==2.9.0",
]
